defaultCiPipeline {
	operatingSystem = ['ubuntu']
	instanceSize = 'medium'

	ciBuildDockerfile = 'javascript.Dockerfile'

	packageId = 'nem-explorer-frontend'

	codeCoverageTool = 'nyc'
	minimumCodeCoverage = 95
}
