openapi: 3.0.2
info:
    $ref: ./info.yaml
tags:
    $ref: ./tags.yaml
paths:
    $ref: ./routes.yaml
externalDocs:
    description: NEM Developers
    url: https://nemproject.github.io/
servers:
    - url: http://localhost:7890
      description: Local development
    - url: http://54.170.97.221:7890
      description: Mainnet NGL Node - SuperAlice
components:
    parameters:
        $ref: ./parameters/_index.yaml
    requestBodies:
        $ref: ./request_bodies/_index.yaml
    schemas:
        $ref: ./schemas/_index.yaml
    responses:
        $ref: ./responses/_index.yaml
