# Node routes
'/node/info':
    get:
        tags:
            - Node
        summary: Gets basic node information.
        description: Gets basic information about the node.
        operationId: nodeInfo
        responses:
            '200':
                description: success
                content:
                    application/json:
                        schema:
                            $ref: ./schemas/NodeDTO.yml

'/node/peer-list/reachable':
    get:
        tags:
            - Node
        summary: Gets an array all reachable nodes.
        description: Gets an array of all nodes with status 'active' in the neighborhood.
        operationId: nodePeerListReachable
        responses:
            '200':
                description: success
                content:
                    application/json:
                        schema:
                            $ref: ./schemas/NodeListDTO.yml
'/node/peer-list/active':
    get:
        tags:
            - Node
        summary: Gets an array with all the active nodes.
        description: Gets an array of active nodes in the neighborhood that are selected for broadcasts.
        operationId: nodePeerListActive
        responses:
            '200':
                description: success
                content:
                    application/json:
                        schema:
                            $ref: ./schemas/NodeListDTO.yml
'/node/peer-list/all':
    get:
        tags:
            - Node
        summary: Gets all the peer nodes.
        description: Gets an array of all known nodes in the neighborhood.
        operationId: nodePeerListAll
        responses:
            '200':
                description: success
                content:
                    application/json:
                        schema:
                            $ref: ./schemas/AllNodesDTO.yml

# Chain routes
'/chain/height':
    get:
        tags:
            - Chain
        summary: Chain Height
        description: Gets the current height of the block chain.
        operationId: chainHeight
        responses:
            '200':
                description: success
                content:
                    application/json:
                        schema:
                            $ref: ./schemas/BlockHeightDTO.yml
'/chain/score':
    get:
        tags:
            - Chain
        summary: Chain Score
        description: Gets the current score of the block chain.
        operationId: chainScore
        responses:
            '200':
                description: success
                content:
                    application/json:
                        schema:
                            $ref: ./schemas/ChainScoreDTO.yml
